import React from 'react';
import { MapContainer, TileLayer, Marker, Popup } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import L from 'leaflet';

// Fix for default Leaflet icon paths in React
import iconRetinaUrl from 'leaflet/dist/images/marker-icon-2x.png';
import iconUrl from 'leaflet/dist/images/marker-icon.png';
import shadowUrl from 'leaflet/dist/images/marker-shadow.png';

delete L.Icon.Default.prototype._getIconUrl;

L.Icon.Default.mergeOptions({
  iconRetinaUrl: iconRetinaUrl,
  iconUrl: iconUrl,
  shadowUrl: shadowUrl,
});

// Custom colored icons for alerts
const createCustomIcon = (color) => {
  return new L.DivIcon({
    className: 'custom-icon',
    html: `<div style="background-color: ${color}; width: 16px; height: 16px; border-radius: 50%; border: 3px solid white; box-shadow: 0 0 6px rgba(0,0,0,0.5);"></div>`,
    iconSize: [16, 16],
    iconAnchor: [8, 8]
  });
};

const iconColors = {
  HIGH: '#ef4444',    // red-500
  MEDIUM: '#f59e0b',  // amber-500
  LOW: '#10b981'      // emerald-500
};

export default function LiveOSINTMap({ findings = [] }) {
  // Center map on the first valid coordinate, otherwise default global
  const center = findings.length > 0 && findings[0].latitude
    ? [parseFloat(findings[0].latitude) || 20, parseFloat(findings[0].longitude) || 0]
    : [20, 0];
  
  const zoom = findings.length > 0 ? 3 : 2;

  return (
    <div className="w-full h-[450px] rounded-xl overflow-hidden border border-gray-200 dark:border-[#1f2937] shadow-lg relative z-0">
      <MapContainer center={center} zoom={zoom} style={{ height: '100%', width: '100%' }}>
        <TileLayer
          attribution='&copy; OpenStreetMap'
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          className="dark:map-tiles-dark"
        />
        {findings.map((finding, idx) => {
          const alertColor = iconColors[finding.alert_level?.toUpperCase()] || iconColors.LOW;
          
          // robust fallback for coordinates
          const lat = parseFloat(finding.latitude) || (20 + (Math.random() * 20 - 10)); // random nearby if not generated by LLM
          const lng = parseFloat(finding.longitude) || (0 + (Math.random() * 40 - 20));

          return (
            <Marker 
              key={idx} 
              position={[lat, lng]}
              icon={createCustomIcon(alertColor)}
            >
              <Popup>
                <div className="min-w-[220px]">
                  <div className="flex items-center gap-2 mb-2">
                    <span className="text-[10px] font-bold px-2 py-0.5 rounded text-white" style={{backgroundColor: alertColor}}>
                      {finding.alert_level?.toUpperCase() || 'LOW'}
                    </span>
                    <span className="text-[10px] text-gray-500 uppercase font-mono">{finding.source_type || 'OSINT'}</span>
                  </div>
                  <h3 className="text-sm font-bold text-gray-900 leading-tight mb-1">{finding.headline}</h3>
                  <p className="text-xs text-gray-700 leading-relaxed mb-2">{finding.summary}</p>
                  <p className="text-[10px] text-gray-400 font-mono mt-1 pt-1 border-t border-gray-100">
                    Loc: {lat.toFixed(4)}, {lng.toFixed(4)}
                  </p>
                </div>
              </Popup>
            </Marker>
          );
        })}
      </MapContainer>
    </div>
  );
}
